### ISSUE TITLE
After clicking on ShieldPeer logo it is not being redirected to /home

### ISSUE THREAD

**Issue by Thewhite33** [gargmegham/ShieldPeer#7]
After clicking on ShieldPeer logo it is expected that it should redirect to /home but is not redirecting to /home

1. Go to 'https://www.shieldpeer.in/home' without being logged-in 
2. Click on 'Demo in the navbar'
3. Now try clicking on shieldpeer logo it won't redirect you to home page

**Expected behavior**
It should redirect me to /home again after clicking on demo

**Screenshots**

![error](https://github.com/gargmegham/ShieldPeer/assets/58523433/aed01e5f-0650-4835-8fab-de55520e73f8)

**Comment by gargmegham** [comment]
@Thewhite33 thanks for taking the time to raise the issue.

Although it was intended behaviour when I developed it. But now I think about it, it must be annoying for a user.
